apiVersion: v1
kind: Pod
metadata:
  name: sa-frontend
  labels:
    app: sa-frontend
spec:
  containers:
    - image: patrickcoutinho/k8s-mastery-sentiment-analysis-frontend
      name: sa-frontend
      ports:
        - containerPort: 80
